### ISSUE TITLE
BelongsToMany results don't load with a modified $primaryKey on either EntityMap

### ISSUE THREAD

**Issue by hexus** [analogueorm/analogue#172] opened 2017-06-22 09:34 UTC
As discussed in #171.

With a simple User and Group mapping, many-to-many relationships load an empty result set if either map has a modified `$primaryKey`.

That is:

`$users = $userMap->with('groups')->get();` means no users will have groups, and vice versa.

In my case, the `GroupMap` has a `$primaryKey` of `'groupid'`. If I rename the column in the database schema to `id`, and remove the custom `$primaryKey` from the map, everything works as expected.

I'm using a custom connection for this, but this happens with or without the custom connection; I've tested both. However, as a result I noticed that the ID was bound as `null` when the query is run, and digging a little deeper it looked like the proxy object that represented the parent of the relationship had no attributes.

**Comment by RemiCollin** [comment] 2017-06-22 09:52
What is your relationship method in your `UserMap` ?

**Comment by hexus** [comment] 2017-06-22 10:49
**User:**
```
/**
 * The User entity map.
 */
class UserMap extends EntityMap
{
	protected $class = User::class;

	protected $table = 'users';

	public function groups(User $user)
	{
		return $this->belongsToMany($user, Group::class, 'user_groups', 'userid', 'groupid', 'groups');
	}
}
```

**Group:**
```
/**
 * The User Group entity map.
 */
class GroupMap extends EntityMap
{
	protected $class = Group::class;

	protected $table = 'groups';

	protected $primaryKey = 'groupid';

	public function parent(Group $group) {
		return $this->belongsTo($group, Group::class, 'parent_id');
	}

	public function subgroups(Group $group) {
		return $this->hasMany($group, Group::class, 'parent_id');
	}

	public function users(Group $group) {
		return $this->belongsToMany($group, User::class, 'user_groups', 'groupid', 'userid', 'users');
	}
}
```

**Comment by hexus** [comment] 2017-06-22 10:54
I tried this in dev-master and actually get undefined index errors from line 255 in `Relationship::getKeysFromResults()`.

If I look at the results, it looks like it's trying to read `groupid` from User results and read `id` from Group results. Something backwards? 😁

**Comment by RemiCollin** [comment] 2017-06-22 11:17
Can you try this :

```php
public function users(Group $group)
	{
		return $this->belongsToMany($group, User::class, 'user_groups', 'userid', 'groupid');
	}
```

**Comment by hexus** [comment] 2017-06-22 11:26
No difference. I'm back on 5.4 now as that's the version we want to use.

I'm pretty sure this is caused by `$primaryKey = 'groupid';`.

**Comment by RemiCollin** [comment] 2017-06-22 11:39
The `belongsToMany`arguments are the name of the keys in the 'user_groups` table, and Analogue will use the `primaryKey` defined on the parent model to perform the join. Maybe that's the issue there ? 

Otherwise, can you paste me the query log performed during the request ?

**Comment by hexus** [comment] 2017-06-22 11:45
Yeah, I know, that's why I don't think those values are the problem. They should be correct, looking at it. 

Here's a log of sorts:

https://pastebin.com/chMLNQXu

The query is listed first, then the bindings, then the query results. As you can see, the binding of the second query is `NULL` instead of an actual ID.

The last output is the `json_encode()` of the result entities.

**Comment by hexus** [comment] 2017-06-22 11:51
Here's the same for `$userMapper->with('groups')->get();`

https://pastebin.com/Jp83BFYZ

**Comment by hexus** [comment] 2017-06-22 16:39
If you need these logs in a more readable format, I can arrange that. 😄 👍

**Comment by RemiCollin** [comment] 2017-06-23 06:41
It's good enough, I just need some time to implement test case to replicate the issue.

**Comment by hexus** [comment] 2017-06-23 14:26
Thanks very much. We're really excited about integrating this ORM with our software.

**Comment by RemiCollin** [comment] 2017-06-27 08:07
I replicated the issue and it happens when eager loading the relation. I'm working on a fix. 

If you need a workaround, you can drop the `->with()` for now and use lazy loading.

**Comment by RemiCollin** [comment] 2017-06-27 12:46
Closing as duplicate of #171

**Closed by RemiCollin** 2017-06-27 12:46 UTC
